### ISSUE TITLE
X in view - Y total users confusing

### ISSUE THREAD

**Issue by bryan-at-looker** [davidtamaki/admin_power_pack#1]
![image](https://user-images.githubusercontent.com/25156666/95004600-411a1000-05a2-11eb-9d68-396a47b359ba.png)

The wording on the user table is a bit confusing. It took me awhile to realize that `20 in view` meant my filtered user set only had 20 rows. I kept trying to go to other pages to select more 😆 . I think it would be more intuitive to either say 20 in filtered table or 20 / 114 total users

**Comment by davidtamaki** [comment]
Makes sense, went with "in filtered table". Updated in [v0.1.2](https://github.com/davidtamaki/admin_power_pack/releases/tag/v0.1.2)
