### ISSUE TITLE
Include "All Users"

### ISSUE THREAD

**Issue by bryan-at-looker** [davidtamaki/admin_power_pack#3]
It took me a bit of time to find the Show: Regular Users dropdown. I couldn't figure out why it said I had 114 users, but the most I could get in the table was 60. Perhaps put Show in a more obvious spot (technically its a filter, maybe there?) and/or have an option for All Users.

**Comment by davidtamaki** [comment]
Moved this down to the **Filters** row and added the "All Users" option, hopefully that's clearer!
Closed in [v0.1.2](https://github.com/davidtamaki/admin_power_pack/releases/tag/v0.1.2)
